GET http://localhost:5000/ticket-booking


### 
POST http://localhost:5000/ticket-booking
Content-Type: application/json

{
    "numberOfTickets": "3",
    "eventId": "14dd3d02-667d-482e-9634-bdfeeeb499b4",
    "userId": "be716b55-8afd-4122-8121-213afc9517ac"
}


###
GET http://localhost:5000/ticket-booking/be716b55-8afd-4122-8121-213afc9517ac



###
DELETE http://localhost:5000/ticket-booking/remove/3399624d-91bd-4db3-aa55-1bb47ebe286d