
GET http://localhost:5000/events


###

POST http://localhost:5000/events/multiple
Content-Type: application/json

[
  {
    "eventName": "Music Festival 2024",
    "description": "An amazing music festival featuring top artists.",
    "eventDateTime": "2024-12-15T18:00:00",
    "category": "Concerts",
    "duration": "180", 
    "totalTickets": "500",
    "location": "Los Angeles, CA",
    "averageRating": "4.5",
    "organizerName": "XYZ Events",
    "organizerImage": "https://example.com/images/xyz_events.jpg",
    "imageUrl": "https://assets-in.bmscdn.com/nmcms/events/banner/weblisting/baking-jokes-a-stand-up-comedy-open-mic-et00339526-2024-5-16-t-5-1-0.jpg",
    "ticketPrice": "75"
  },
  {
    "eventName": "Tech Conference 2024",
    "description": "Join us for an insightful tech conference with industry leaders.",
    "eventDateTime": "2024-11-20T09:00:00",
     "category": "Conferences",
    "duration": "360",
    "totalTickets": "300",
    "location": "San Francisco, CA",
    "averageRating": "4.7",
    "organizerName": "TechWorld",
    "organizerImage": "https://example.com/images/techworld.jpg", 
    "imageUrl": "https://assets-in.bmscdn.com/nmcms/events/banner/weblisting/tag-maadu-kannada-comedy-every-friday-et00411360-2024-9-10-t-6-37-23.jpg",
    "ticketPrice": "150"
  }
  
]

### Update Event by ID

PUT http://localhost:5000/events/update/091e0ff9-5053-4f2b-9a24-f6e2f19a33e6
Content-Type: application/json

{
  "eventName": "Anirudh Ravichandran Concert"
}


### Delete Event By ID
DELETE  http://localhost:5000/events/remove/0cd4a97e-7cd5-426d-8783-3a98ff5f0d6b