
GET http://localhost:5000/wishlist

###
POST http://localhost:5000/wishlist
Content-Type: application/json

{
    "userId":"51c8ccba-7994-46cd-a9e9-03f097a268dc",
    "eventId":"92ed98d8-f937-439e-a92f-7bf126bf0c82"
}

###
DELETE  http://localhost:5000/wishlist/92ed98d8-f937-439e-a92f-7bf126bf0c82